language: ruby
rvm: 2.2.2
addons:
  postgresql: '9.3'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
script:
- RAILS_ENV=test bundle exec rake db:migrate
- RAILS_ENV=test bundle exec rspec
branches:
  only:
  - develop
  - master
after_success:
- coveralls
deploy:
  provider: heroku
  app: salty-ridge-48765
  api_key:
    secure: GqjlTGrXzV8VqZvv6OT13KOaCIaw1oKgNgEL4QnF3GMf1RPerFewnRERo9j6/NswRk4yyDJeCajzXdSpCnfmtDRlvIeHy5WcbajgUhYAmGmYQBhePZckGPwgLC++979uD+oSAbY+e70vO66WhHvtQVKmn2/picDFICsnS1264YxjBW9yMuu4XQwmqLLzHYhcnfi8m/YnavPvnxS+lv1XgvSWhxUkLE16RM4vhYdC7MN0IT52148aDMbSARj9fZDwFmA7GusMRJKLZCrrTg3Mduy/UJN4isvAw1F+aiHXO5TMnYa+kra+7j6zJ0qZUqNEyAbTYKRALhMmcwwSVB6wkemb/M6fOMdT/0euIaFeqWhn1bLfSIIveLjQx758lDHma9iZf3fEvhzOwROA4Dkp4XrRGykMg5KRdk1TqPHN3uho3HdoiXwqH82oH4QzhVZuFuva01xeyJVinmPmklB8BMfT6yeLI4gTtJG5rva8G5PxLpGdONTl8e5/ouPTiOp6p8ToBXqS98itGD3goWeNFeGU8KOjUDwKcR7sw2hyeWamBJTkA0PLgJ1CM0pSmeSdXsh9yNkWXFpPqIK7136WdOqbvfF3jizS6VnI9dFrGGCqtIjfhHNp8pJNMzywsK/9aKFqXdgk07knkz4Eu935ulXUYj6uh5l4XRHPpyIG7nY=
  run:
    - 'rake db:migrate'
